name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/ModernizedApp/ModernizedApp.csproj
      - name: Build
        run: dotnet build src/ModernizedApp/ModernizedApp.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test tests/ModernizedApp.Tests/ModernizedApp.Tests.csproj --no-build --verbosity normal
